# Generated by Django 3.0.2 on 2020-04-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_copon'),
    ]

    operations = [
        migrations.AddField(
            model_name='copun',
            name='amount',
            field=models.FloatField(default=20.0),
            preserve_default=False,
        ),
    ]
