# Generated by Django 3.0.2 on 2020-04-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200421_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('L', 'LG'), ('H', 'Huawei'), ('A', 'Apple')], default='SW', max_length=2),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
